### ISSUE TITLE
publish to melpa

### ISSUE THREAD

**Issue by kidd** [kidd/git-msg-prefix#3]

**Comment by stardiviner** [comment]
any update on publish to MELPA?

**Comment by kidd** [comment]
not really... The thing is that there are a few concerns that I'm not sure how to solve them. 
https://github.com/melpa/melpa/pull/5105 

Maybe the whole commit-msg-prefix is too ad-hoc even to be in melpa.  

I'll give it another thought and see if I push it forward. Any opinions about the concerns in the melpa PR will be taken into account :)

**Comment by stardiviner** [comment]
About `defgroup` and `defcustom` you can check out other packages code example. It's very simple.
About `ido` completing framework. You can add an option to whether user want to force this package to use `ido` instead of Emacs default `completing-read`. I suggest use `completing-read` by default. So the `defcustom` option value should be nil by default. What do you think?
And add an `defcustom` alist for storing user custom defined a list of prefix words. This will be great.

**Comment by kidd** [comment]
done. enjoy :)

**Comment by stardiviner** [comment]
Thanks for your work, installed. Great.
