### ISSUE TITLE
Allow reading prefix from branch name

### ISSUE THREAD

**Issue by DamienCassou** [kidd/git-msg-prefix#5]
In our team, the branch name starts with the issue number the branch is supposed to fix. This is also what gitlab does by default when a developer clicks "Create a merge request" from an issue. Could commit-msg-prefix also allow taking the prefix from the branch name?

**Comment by kidd** [comment]
Hi, 
Yes, that should be possible, but if the pattern is a very fixed one, maybe the choice menu doesn't make sense then either.

What should be the alternatives? all local branch names? That is definitely possible, but the menu itself seems pointless because you are already in the branch that has the correct naming.

Any ideas/suggestions?
Cheers!

**Comment by DamienCassou** [comment]
"Raimon Grau (rgrau)" <notifications@github.com> writes:
> Yes, that should be possible, but if the pattern is a very fixed one,
> maybe the choice menu doesn't make sense then either.
>
> What should be the alternatives? all local branch names? That is
> definitely possible, but the menu itself seems pointless because you
> are already in the branch that has the correct naming.

what about adding the current local branch name to the list of previous
commits directly?

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by kidd** [comment]
I added support for that one. Let's see if it's useful enough to stay  :)

Thanks for your suggestion!

**Comment by DamienCassou** [comment]
Thank you
